QOH_intro3/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :diaries do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :events

  get 'users/:id/favorites' => 'users#favorites', as: 'user_favorites'
  get 'users/:id/graphs' => 'users#graphs', as: 'user_graphs'
  get 'search' => 'search#search'
  get 'my_calendar', to: 'events#my_calendar'
  root 'homes#top'
  get 'home/about' => 'homes#about'
end

QOH_intro3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image, destroy: false
  has_many :diaries, dependent: :destroy
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_diaries, through: :favorites, source: 'diary'
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  validates :nickname, presence: true, length: { maximum: 20 }, uniqueness: true

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

QOH_intro3/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

QOH_intro3/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

QOH_intro3/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

QOH_intro3/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  prepend_before_action :check_captcha, only: [:create]

  private

    def check_captcha
      self.resource = resource_class.new sign_up_params
      resource.validate
      unless verify_recaptcha(model: resource)
        respond_with_navigational(resource) { render :new }
      end
    end
end

QOH_intro3/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

QOH_intro3/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

QOH_intro3/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@diaries = @user.diaries.page(params[:page]).reverse_order


		days = (Date.today.beginning_of_week..Date.today).to_a
        exercises = days.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.exercise&.to_i}

        @graph = LazyHighCharts::HighChart.new('graph') do |f|
        	   f.title(text: '運動時間(週)')
        	   f.xAxis(categories: days)
        	   f.series(name: '時間', data: exercises)
        	   f.chart(type: "column")
        end

        sleeps = days.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.sleep&.to_i}
        @graph2 = LazyHighCharts::HighChart.new('graph') do |f|
		     f.title(text: '睡眠時間(週)')
		     f.xAxis(categories: days)
		     f.series(name: '時間', data: sleeps)
		     f.chart(type: "column")
		end

		cigarettes = days.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.cigarette&.to_i}
        @graph3 = LazyHighCharts::HighChart.new('graph') do |f|
        	f.title(text: '喫煙本数(週)')
        	f.xAxis(categories: days)
        	f.series(name: '本', data: cigarettes)
        	f.chart(type: "column")
        end

        drinkings = days.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.drinking&.to_i}
        @graph4 = LazyHighCharts::HighChart.new('graph') do |f|
		     f.title(text: '飲酒量(週)')
		     f.xAxis(categories: days)
		     f.series(name: '缶', data: drinkings)
		     f.chart(type: "column")
		end
	end

	def graphs
		@user = User.find(params[:id])

		days2 = (Date.today.beginning_of_month..Date.today).to_a
		days3 = (Date.today.beginning_of_year..Date.today).to_a

		exercises_m = days2.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.exercise&.to_i}
		exercises_y = days3.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.exercise&.to_i}
        @graph_m = LazyHighCharts::HighChart.new('graph') do |f|
        	   f.title(text: '運動時間(月)')
        	   f.xAxis(categories: days2)
        	   f.series(name: '時間', data: exercises_m)
        	   f.chart(type: "column")
        end
        @graph_y = LazyHighCharts::HighChart.new('graph') do |f|
        	   f.title(text: '運動時間(年)')
        	   f.xAxis(categories: days3)
        	   f.series(name: '時間', data: exercises_y)
        	   f.chart(type: "column")
        end

        
        sleeps_m = days2.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.sleep&.to_i}
        sleeps_y = days3.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.sleep&.to_i}
        @graph2_m = LazyHighCharts::HighChart.new('graph') do |f|
		     f.title(text: '睡眠時間(月)')
		     f.xAxis(categories: days2)
		     f.series(name: '時間', data: sleeps_m)
		     f.chart(type: "column")
		end
		@graph2_y = LazyHighCharts::HighChart.new('graph') do |f|
		     f.title(text: '睡眠時間(年)')
		     f.xAxis(categories: days3)
		     f.series(name: '時間', data: sleeps_y)
		     f.chart(type: "column")
		end

		
		cigarettes_m = days2.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.cigarette&.to_i}
		cigarettes_y = days3.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.cigarette&.to_i}
        @graph3_m = LazyHighCharts::HighChart.new('graph') do |f|
        	f.title(text: '喫煙本数(月)')
        	f.xAxis(categories: days2)
        	f.series(name: '本', data: cigarettes_m)
        	f.chart(type: "column")
        end
        @graph3_y = LazyHighCharts::HighChart.new('graph') do |f|
        	f.title(text: '喫煙本数(年)')
        	f.xAxis(categories: days3)
        	f.series(name: '本', data: cigarettes_y)
        	f.chart(type: "column")
        end


        drinkings_m = days2.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.drinking&.to_i}
        drinkings_y = days3.map {|day| @user.diaries.find{|x| x.created_at.to_date == day}&.drinking&.to_i}
        @graph4_m = LazyHighCharts::HighChart.new('graph') do |f|
		     f.title(text: '飲酒量(月)')
		     f.xAxis(categories: days2)
		     f.series(name: '缶', data: drinkings_m)
		     f.chart(type: "column")
		end
		@graph4_y = LazyHighCharts::HighChart.new('graph') do |f|
		     f.title(text: '飲酒量(年)')
		     f.xAxis(categories: days3)
		     f.series(name: '缶', data: drinkings_y)
		     f.chart(type: "column")
		end
	end

	def index
		@users = User.all
	end

	def favorites
		@user = User.find(params[:id])
		@diaries = @user.favorite_diaries.page(params[:page]).reverse_order
	end


	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
		   redirect_to user_path(current_user)
		else
			render 'edit'
		end
	end

	def follows
	end

	def followers
	end

	private

	def user_params
        params.require(:user).permit(:nickname, :profile, :profile_image)
    end
end

QOH_intro3/app/helpers/users_helper.rb
module UsersHelper
end

QOH_intro3/app/views/users/_follow.html.erb
<% if current_user.following?(user) %>
     <%= link_to 'フォロー中', user_relationships_path(user.id), method: :delete, data: {confirm: "フォローから外しますか？"}, class: "btn btn-primary" %>
<% else %>
     <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
<% end %>

QOH_intro3/app/views/users/_index.html.erb
<div class="col-md-10 col-sm-10 col-xs-12">
  <div class="box">
    <table class="table table-striped">
        <thead>
         <tr>
            <th>アイコン</th>
            <th>ユーザー</th>
            <th>プロフィール</th>
            <th></th>
         </tr>
        </thead>
      <tbody>
          <% users.each do |user| %>
            <tr>
               <td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "noimage.png", size: '100x100', class: "appli_img") %></td>
               <td><%= user.nickname%></td>
               <td><%= user.profile %></td>
               <td><%= link_to '詳細', user_path(user), method: :get, class: "btn btn-primary" %></td>
             </tr>
          <% end %>
      </tbody>
     </table>
  </div>
</div>

QOH_intro3/app/views/users/edit.html.erb
<div class="container">
	<div class="row">
        <div class="col-md-3 col-sm-3 col-xs-3">
            <%= render 'diaries/error-message', model: @user %>
        </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2 class="font_img">プロフィール編集</h2>
                    <%= form_for(@user) do |f| %>
                 <div class="field">
              		  <%= f.file_field :profile_image, class: 'img_field', style: 'display:none;' %>
              		  <%= attachment_image_tag @user, :profile_image, :fill, 300, 300, fallback: 'noimage.png', size: '300x300', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev' %>
                 </div>
                 <div class="field">
                 	  <%= f.label :nickname, 'ネーム' %><br>
                 	  <%= f.text_field :nickname, autofocus: true, class: "nickname form-control" %>
                 </div>
                 <div class="field" style="margin-bottom: 20px;">
                 	  <%= f.label :profile, '自己紹介' %><br>
                 	  <%= f.text_area :profile, autofocus: true, size: "90x5", class: "profile form-control" %>
                 </div>
                 <div class="actions">
                      <%= f.submit '登録', class: "btn btn-success form-control" %>
                 </div>
                    <% end %>
             </div>
         <div class="col-md-3 col-sm-3 col-xs-3"></div>
    </div>
</div>

QOH_intro3/app/views/users/favorites.html.erb
<div class="container">
	<div class="row">
      <h2 class="font_img"><%= @user.nickname %>のお気に入り一覧</h2>
        <div class="col-md-12 col-sm-12 col-xs-12">
			<%= render 'diaries/index', diaries: @diaries %>
			<%= paginate @diaries %>
		</div>
	</div>
</div>

QOH_intro3/app/views/users/follow.js.erb
$("#follow-button_<%= @user.id %>").html("<%= j(render 'users/follow', user: @user) %>");
$("#follower-count_<%= @user.id %>").html('<%= link_to "#{ @user.followed.count}フォロワー", user_followers_path(@user) %>');
$("#following-count_<%= @user.id %>").html('<%= link_to "#{ @user.follower.count}フォロー", user_follows_path(@user) %>');

QOH_intro3/app/views/users/graphs.html.erb
<div class="container">
	<div class="col-md-12 col-sm-12 col-xs-12">
	    <h1 class="font_img"><%= @user.nickname %>の実績</h1>
	</div>
	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="box">
	       <%= high_chart('my_chart_m', @graph_m) %>
	       <%= high_chart('my_chart_y', @graph_y) %>
	   </div>
	   <div class="box">
	       <%= high_chart('my_chart2_m', @graph2_m) %>
	       <%= high_chart('my_chart2_y', @graph2_y) %>
	   </div>
	   <div class="box">
	       <%= high_chart('my_chart3_m', @graph3_m) %>
	       <%= high_chart('my_chart3_y', @graph3_y) %>
	   </div>
	   <div class="box">
	       <%= high_chart('my_chart4_m', @graph4_m) %>
	       <%= high_chart('my_chart4_y', @graph4_y) %>
	   </div>
	</div>
</div>

QOH_intro3/app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3 col-sm-3 col-xs-12">
			<table class="table">
				<tr><%= attachment_image_tag @user, :profile_image, :fill, 180, 180, fallback: "noimage.png", size: "200x200", class: "appli_img" %></tr>
				<tr>
	                <th>ネーム</th>
					<th><%= @user.nickname %></th>
				</tr>
				<tr>
				    <th>プロフィール</th>
					<th><%= @user.profile %></th>
				</tr>
				<tr>
					<th><%= link_to "お気に入りの日記", user_favorites_path(@user) %></th>
				</tr>
				<tr>
					<th><%= link_to "#{ @user.follower.count}フォロー", user_follows_path(@user) %></th>
					<th><%= link_to "#{ @user.followed.count}フォロワー", user_followers_path(@user) %></th>
				</tr>
			</table>
			<% unless @user == current_user  %>
			<span>
			<%= render 'users/follow', user: @user %>
		    </span>
			<% end %>
			  <% if @user == current_user %>
					<%= link_to 'プロフィール編集', edit_user_path(@user), class: "col-xs-12 btn btn-default edit_user_#{@user.id}" %>
					  <div id="calendar"></div>
					<%= link_to 'カレンダー詳細', my_calendar_path, class: "btn btn-default" %>
			  <% end %>
	    </div>
	    <div class="col-md-9 col-sm-9 col-xs-12">
           <h2 class="font_img"><%= @user.nickname %>の記録</h2><%= paginate @diaries %>
        </div>
        <div class="col-md-9 col-sm-9  col-xs-12">
				<% @diaries.each do |diary| %>
				<div class="col-md-4 col-sm-6 col-xs-12">
					<div class="box">
						<div class="index_lists">
							<p class="show_back" style="padding-left: 60px;"><%= diary.user.nickname %>の日記</p><br>
							<p><%= link_to diary_path(diary) do %>
							    <%= attachment_image_tag diary, :body_image, :fill, 150, 150, fallback: "diary_no.png", size: '150x150', class: "appli_img3 index_img" %>
							   <% end %></p><br>
							   <%= link_to diary_path(diary) do %>
								   <span class="diary_point">コメントする</span>
							   <% end %><br>
							<p class="tag_area"><%= render 'diaries/tag_list', tag_list: diary.tag_list %></p>
							<p class="show_back">投稿日　<%= diary.created_at.strftime('%Y/%m/%d') %></p>
							<p class="sentiment-score">
								<% if diary.score == nil %>
                                  この日記にはスコアがありません
                                <% else %>
                                  日記の感情分析スコア<%= diary.score %>点
                                <% end %>
							</p>
				        </div>
				    </div>
				</div>
				<% end %>
	    </div>
	</div>
	    <div class="row">
		    <div class="col-md-6 col-sm-6 col-xs-12">
		    	<div class="box">
			       <%= high_chart('my_chart', @graph) %>
			   </div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
			   <div class="box">
			       <%= high_chart('my_chart2', @graph2) %>
			   </div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
			   <div class="box">
			       <%= high_chart('my_chart3', @graph3) %>
			   </div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
			   <div class="box">
			       <%= high_chart('my_chart4', @graph4) %>
			   </div>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12"></div>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<%= link_to 'さらに詳しく見る', user_graphs_path, class: 'btn btn-success btn-block' %>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12"></div>
		</div>

</div>

QOH_intro3/app/views/users/unfollow.js.erb
$("#follow-button_<%= @user.id %>").html("<%= j(render 'users/follow', user: @user) %>");
$("#follower-count_<%= @user.id %>").html('<%= link_to "#{ @user.followed.count}フォロワー", user_followers_path(@user) %>');
$("#following-count_<%= current_user.id %>").html('<%= link_to "#{ @user.follower.count}フォロー", user_follows_path(@user) %>');