config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :diaries do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :notifications, only: :index
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :index, :show]
  resources :events

  delete '/notifications/destroy_all' => 'notifications#destroy_all'
  get 'users/:id/favorites' => 'users#favorites', as: 'user_favorites'
  get 'users/:id/graphs' => 'users#graphs', as: 'user_graphs'
  get 'search' => 'search#search'
  get 'my_calendar', to: 'events#my_calendar'
  root 'homes#top'
  get 'home/about' => 'homes#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image, destroy: false
  has_many :diaries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_diaries, through: :favorites, source: 'diary'
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :nickname, presence: true, length: { maximum: 20 }, uniqueness: true
  validates :profile, length: { maximum: 50 }

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
 end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  prepend_before_action :check_captcha, only: [:create]

  private

  def check_captcha
    self.resource = resource_class.new sign_up_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.page(params[:page]).reverse_order.per(4)

    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end

    days = (Date.today.beginning_of_week..Date.today).to_a
    exercises = days.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.exercise&.to_i }

    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '運動時間(週)')
      f.xAxis(categories: days)
      f.series(name: '時間', data: exercises)
      f.chart(type: "column")
    end

    sleeps = days.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.sleep&.to_i }
    @graph2 = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '睡眠時間(週)')
      f.xAxis(categories: days)
      f.series(name: '時間', data: sleeps)
      f.chart(type: "column")
    end

    cigarettes = days.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.cigarette&.to_i }
    @graph3 = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '喫煙本数(週)')
      f.xAxis(categories: days)
      f.series(name: '本', data: cigarettes)
      f.chart(type: "column")
    end

    drinkings = days.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.drinking&.to_i }
    @graph4 = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '飲酒量(週)')
      f.xAxis(categories: days)
      f.series(name: '缶', data: drinkings)
      f.chart(type: "column")
    end
  end

  def graphs
    @user = User.find(params[:id])

    days2 = (Date.today.beginning_of_month..Date.today).to_a
    days3 = (Date.today.beginning_of_year..Date.today).to_a

    exercises_m = days2.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.exercise&.to_i }
    exercises_y = days3.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.exercise&.to_i }
    @graph_m = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '運動時間(月)')
      f.xAxis(categories: days2)
      f.series(name: '時間', data: exercises_m)
      f.chart(type: "column")
    end
    @graph_y = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '運動時間(年)')
      f.xAxis(categories: days3)
      f.series(name: '時間', data: exercises_y)
      f.chart(type: "column")
    end

    sleeps_m = days2.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.sleep&.to_i }
    sleeps_y = days3.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.sleep&.to_i }
    @graph2_m = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '睡眠時間(月)')
      f.xAxis(categories: days2)
      f.series(name: '時間', data: sleeps_m)
      f.chart(type: "column")
    end
    @graph2_y = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '睡眠時間(年)')
      f.xAxis(categories: days3)
      f.series(name: '時間', data: sleeps_y)
      f.chart(type: "column")
    end

    cigarettes_m = days2.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.cigarette&.to_i }
    cigarettes_y = days3.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.cigarette&.to_i }
    @graph3_m = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '喫煙本数(月)')
      f.xAxis(categories: days2)
      f.series(name: '本', data: cigarettes_m)
      f.chart(type: "column")
    end
    @graph3_y = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '喫煙本数(年)')
      f.xAxis(categories: days3)
      f.series(name: '本', data: cigarettes_y)
      f.chart(type: "column")
    end

    drinkings_m = days2.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.drinking&.to_i }
    drinkings_y = days3.map { |day| @user.diaries.find { |x| x.created_at.to_date == day }&.drinking&.to_i }
    @graph4_m = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '飲酒量(月)')
      f.xAxis(categories: days2)
      f.series(name: '缶', data: drinkings_m)
      f.chart(type: "column")
    end
    @graph4_y = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: '飲酒量(年)')
      f.xAxis(categories: days3)
      f.series(name: '缶', data: drinkings_y)
      f.chart(type: "column")
    end
  end

  def index
    @users = User.all
  end

  def favorites
    @user = User.find(params[:id])
    @diaries = @user.favorite_diaries.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def follows
  end

  def followers
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :profile, :profile_image)
    end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/views/users/_user-diary.html.erb
<% diaries.each do |diary| %>
	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="box">
			<div class="index_lists">
				<p class="show_back" style="padding-left: 60px;"><%= diary.user.nickname %>の日記</p><br>
				<p><%= link_to diary_path(diary) do %>
				    <%= attachment_image_tag diary, :body_image, :fill, 150, 150, fallback: "diary_no.png", size: '150x150', class: "appli_img3 index_img" %>
				   <% end %></p><br>
				   <%= link_to diary_path(diary) do %>
					   <span class="diary_point">コメントする</span>
				   <% end %><br>
				<p class="tag_area"><%= render 'diaries/tag_list', tag_list: diary.tag_list %></p>
				<p class="show_back">投稿日　<%= diary.created_at.strftime('%Y/%m/%d') %></p>
				<p class="sentiment-score">
					<% if diary.score == nil %>
	                  この日記にはスコアがありません
	                <% else %>
	                  日記の感情分析スコア<%= diary.score %>点
	                <% end %>
				</p>
	        </div>
	    </div>
	</div>
<% end %>

app/views/users/_user-prof.html.erb
<table class="table">
	<tr><%= attachment_image_tag user, :profile_image, :fill, 180, 180, fallback: "noimage.png", size: "200x200", class: "appli_img" %></tr>
	<tr>
        <th>ネーム</th>
		<th><%= user.nickname %></th>
	</tr>
	<tr>
	    <th>プロフィール</th>
		<th><%= user.profile %></th>
	</tr>
	<tr>
		<th><%= link_to "お気に入りの日記", user_favorites_path(user) %></th>
		<th></th>
	</tr>
	<tr>
		<th><%= link_to "#{ @user.follower.count}フォロー", user_follows_path(user) %></th>
		<th><%= link_to "#{ @user.followed.count}フォロワー", user_followers_path(user) %></th>
	</tr>
</table>
<% unless user == current_user  %>
<span>
<%= render 'users/follow', user: user %>
</span>
<% end %>
  <% if user == current_user %>
		<%= link_to 'プロフィール編集', edit_user_path(user), class: "col-xs-12 btn btn-default edit_user_#{user.id}" %>
		  <div id="calendar"></div>
		<%= link_to 'カレンダー詳細', my_calendar_path, class: "btn btn-default" %>
  <% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3 col-sm-3 col-xs-12">
			<%= render 'users/user-prof', user: @user %>
			<% unless @user.id == current_user.id %>
			  <% if @is_room == true %>
			    <%= link_to 'メッセージ', room_path(@room_id), class: 'btn-sm btn-success' %>
			  <% else %>
			    <%= form_with model: @room, url: rooms_path, local: true do |f| %>
			      <%= fields_for @entry do |e| %>
				      <%= e.hidden_field :user_id, value: @user.id %>
				      <%= f.submit 'メッセージ', class: 'btn-sm btn-success' %>
			      <% end %>
			    <% end%>
			  <% end %>
			<% end %>
	    </div>
	    <div class="col-md-6 col-sm-6 col-xs-12">
           <h2 class="font_img"><%= @user.nickname %>の記録</h2><%= paginate @diaries %>
        </div>
        <div class="col-md-6 col-sm-6  col-xs-12">
		   <%= render 'users/user-diary', diaries: @diaries %>
	    </div>
	    <div class="col-md-3 col-sm-3 col-xs-12">
	    </div>
	</div>
	    <div class="row">
		    <div class="col-md-6 col-sm-6 col-xs-12">
		    	<div class="box">
			       <%= high_chart('my_chart', @graph) %>
			   </div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
			   <div class="box">
			       <%= high_chart('my_chart2', @graph2) %>
			   </div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
			   <div class="box">
			       <%= high_chart('my_chart3', @graph3) %>
			   </div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
			   <div class="box">
			       <%= high_chart('my_chart4', @graph4) %>
			   </div>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12"></div>
			<div class="col-md-6 col-sm-6 col-xs-12">
				<%= link_to 'さらに詳しく見る', user_graphs_path, class: 'btn btn-success btn-block' %>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12"></div>
		</div>

</div>