QOH_intro3/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :diaries do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :events

  get 'users/:id/favorites' => 'users#favorites', as: 'user_favorites'
  get 'users/:id/graphs' => 'users#graphs', as: 'user_graphs'
  get 'search' => 'search#search'
  get 'my_calendar', to: 'events#my_calendar'
  root 'homes#top'
  get 'home/about' => 'homes#about'
end

QOH_intro3/app/models/diary.rb
class Diary < ApplicationRecord
    acts_as_taggable
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :body_image, destroy: false
	validates :body, presence: true, length: { maximum: 200 }
	validates :exercise, presence: true
	validates :sleep, presence: true
	validates :cigarette, presence: true
	validates :drinking, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

QOH_intro3/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

	def new
		@diary = Diary.new
	end

	def create
		@diary = Diary.new(diary_params)
		@diary.user_id = current_user.id
		@diary.score = Language.get_data(diary_params[:body])
		if @diary.save
		   redirect_to user_path(current_user)

		else
			render 'new'
		end
	end

	def index
		   @diaries = Diary.page(params[:page]).reverse_order
		if params[:tag_name]
           @diaries = Diary.tagged_with("#{params[:tag_name]}").page(params[:page]).reverse_order
        end
	end

	def show
		@diary = Diary.find(params[:id])
		@comment = Comment.new
        @comments = @diary.comments
	end

	def edit
		@diary = Diary.find(params[:id])
	end

	def update
		@diary = Diary.find(params[:id])
		
		if @diary.update(diary_params)
		   redirect_to user_path(current_user)

		else
			render 'edit'
		end
	end

	def destroy
		@diary = Diary.find(params[:id])
		@diary.destroy
		redirect_to user_path(current_user)
	end

	private

	def diary_params
		params.require(:diary).permit(:body, :body_image, :exercise, :sleep, :cigarette, :drinking, :tag_list)
	end
end

QOH_intro3/app/helpers/diaries_helper.rb
module DiariesHelper
end

QOH_intro3/app/views/diaries/_comment-area.html.erb
<% comments.each do |comment| %>
  <p class="comment_back">
      <%= link_to user_path(comment.user), class: "user_#{comment.user.id}" do %>
           <%= attachment_image_tag comment.user, :profile_image, fallback: "noimage.png", size: "50x50", class: "appli_img" %>
      <% end %>
           <%= comment.user.nickname %>さんからのコメント
      <% if current_user == comment.user %>
           <%= link_to '', diary_comment_path(comment), class: 'btn btn-default glyphicon glyphicon-trash bt_del', method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
      <% end %>
  </p>
        <p><%= comment.comment %></p>
<% end %>

QOH_intro3/app/views/diaries/_error-message.html.erb
<% if model.errors.any? %>
	<div id="error_explanation">
		<h3>下記の項目を修正してください</h3>
		<ul>
			<% model.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

QOH_intro3/app/views/diaries/_favorite.html.erb
<% if diary.favorited_by?(current_user) %>
   <%= link_to diary_favorites_path(diary), method: :delete, remote: true  do %>
       <span class="glyphicon glyphicon-heart" style="color: red;"><%= diary.favorites.count%></span>
   <% end %>
<% else %>
   <%= link_to diary_favorites_path(diary), method: :post, remote: true  do %>
       <span class="glyphicon glyphicon-heart-empty"><%= diary.favorites.count %></span>
   <% end %>
<% end %>

QOH_intro3/app/views/diaries/_index.html.erb
<% diaries.each do |diary| %>
	<div class="col-md-4 col-sm-6 col-xs-12">
		<div class="box">
			<div class="index_lists">
				<p class="show_back" style="font-size: 20px; padding-left: 60px;"><%= diary.user.nickname %>の日記</p><br>
				<p><%= link_to diary_path(diary) do %>
				        <%= attachment_image_tag(diary, :body_image, :fill, 200, 200, fallback: "diary_no.png", size: '200x200', class: "appli_img3 index_img") %>
				   <% end %></p><br>
				<p><%= link_to diary_path(diary) do %>
					    <span class="diary_point">コメントする</span>
				   <% end %></p><br>
				<p class="tag_area"><%= render 'diaries/tag_list', tag_list: diary.tag_list %></p>
				<p class="show_back" style="padding-left: 60px;">投稿日　<%= diary.created_at.strftime('%Y/%m/%d') %></p>
				<p class="sentiment-score">
                   <% if diary.score == nil %>
                      この日記にはスコアがありません
                   <% else %>
                      日記の感情分析スコア<%= diary.score %>点
                   <% end %>
				</p>
			</div>
		</div>
	</div>
<% end %>

QOH_intro3/app/views/diaries/_new-diary.html.erb
<div class="col-md-7 col-sm-7 col-xs-12">
    <button id="tutorial">チュートリアル開始</button>
  <%= form_for(diary) do |f| %>
    <div class="field">
    	<%= f.label :tag_list, 'タグ  (タグはカンマ区切りで複数入力できます)' %><br>
    	<%= f.text_field :tag_list, value: @diary.tag_list.join(','), class: "form-control", id: 'introjs-step1' %>
    </div>

    <div class="field">
        <%= f.label :body, '本文(※必須)' %><br>
        <%= f.text_area :body, size: "90x10", class: "diary_body form-control", id: 'introjs-step2' %>
    </div>
    <h4>本日の実績を入力してください(※必須)　※飲酒量は350ml缶で1とします</h4>
    <div class="field" style="margin-bottom: 5px;">
    	<%= f.number_field :exercise , placeholder: "運動時間", class: "form-control", id: 'introjs-step3' %>
    </div>

    <div class="field" style="margin-bottom: 5px;">
    	<%= f.number_field :sleep , placeholder: "睡眠時間", class: "form-control", id: 'introjs-step4' %>
    </div>

    <div class="field" style="margin-bottom: 5px;">
    	<%= f.number_field :cigarette , placeholder: "喫煙本数", class: "form-control", id: 'introjs-step5' %>
    </div>

    <div class="field">
    	<%= f.number_field :drinking , placeholder: "飲酒量", class: "form-control", id: 'introjs-step6' %>
    </div>
</div>

<div class="col-md-4 col-sm-4 col-xs-12">
        <%= f.file_field :body_image, class: 'img_field', style: 'display:none;' %>
        <%= attachment_image_tag diary, :body_image, :fill, 200, 200, fallback: 'diary_no.png', size:'300x300', onClick: "$('.img_field').click()", class: 'center-block img-thumbnail img-responsive img_prev', id: 'introjs-step7' %>

    <div class="field" style="margin-top: 15px;">
    	<%= f.submit '投稿', class: "btn btn-success form-control", id: 'introjs-step8'  %>
    </div>
  <% end %>
</div>

QOH_intro3/app/views/diaries/_tag_list.html.erb
<% tag_list.each do |tag| %>
#<%= link_to tag, diaries_path(tag_name: tag), class: "label label-success" %>
<% end %>

QOH_intro3/app/views/diaries/edit.html.erb
<div class="container">
    <div class="row">
        <h2 class="font_img">編集ページ</h2>
        <%= render 'diaries/new-diary', diary: @diary %>
    </div>
</div>

QOH_intro3/app/views/diaries/index.html.erb
<div class="container">
    <div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
				<h2 class="font_img">投稿一覧</h2>
				 <%= render 'diaries/index', diaries: @diaries %>
				<%= paginate @diaries %>
		</div>
	</div>
</div>

QOH_intro3/app/views/diaries/new.html.erb
<div class="container">
	<div class="row">
        <h2 class="font_img">新規投稿ページ</h2>
        <%= render 'diaries/new-diary', diary: @diary %>
    </div>
</div>

QOH_intro3/app/views/diaries/show.html.erb
<div class="container">
	<div class="row">
  	  <div class="col-md-5 col-sm-6 col-xs-12">
    	  	<div class="box">
    	  		<p class="show_back"><%= @diary.user.nickname %>の日記</p>
    	  		  <p style="padding-left: 30px;">
                <%= attachment_image_tag(@diary, :body_image, :fill, 300, 300, fallback: "diary_no.png", size:'300x300', class: "appli_img3") %>
              </p>
    	  	</div>
  	  </div>
      <div class="col-md-7 col-sm-6 col-xs-12">
      	<div class="box">
      		<div class="index_show">
      			<p class="show_back">
      				  <%= link_to user_path(@diary.user) do %>
      			　　  <%= attachment_image_tag(@diary.user, :profile_image, :fill, 30, 30, fallback: "noimage.png", size:'50x50', class: "appli_img") %>
      			     <%= @diary.user.nickname %>
      			    <% end %>
      		　　 <span class="tag_area"><%= render 'diaries/tag_list', tag_list: @diary.tag_list %></span>
      	　　　 投稿日<%= @diary.created_at.strftime('%Y/%m/%d') %>
        			        <% if @diary.user == current_user %>
                        <%= link_to "", diary_path(@diary), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-default glyphicon glyphicon-trash bt_del destroy_diary_#{@diary.id}" %>
          			        <%= link_to '', edit_diary_path(@diary), class: "btn btn-default glyphicon glyphicon-wrench bt_del edit_diary_#{@diary.id}" %>
                      <% end %>
      			</p>
      			<p><li><%= @diary.body %></li></p>
      			<p class="show_back">
      				        <span class="diary_<%= @diary.id %>">
                        <%= render 'diaries/favorite', diary: @diary %>
                      </span>
                      <span class="sentiment-score">コメント数：<%= @diary.comments.count %></span>
                      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a>
                  <div class="icon_area">
			                   <span class="show_icon">
			                        <%= image_tag 'exercise.png', size:'30x30', class: "icon_tag" %>
			                        <%= @diary.exercise %>時間
			                   </span>
			                   <span class="show_icon">
			                        <%= image_tag 'sleep.png', size:'30x30', class: "icon_tag" %>
			                   	    <%= @diary.sleep %>時間
			                   </span>
			                   <span class="show_icon">
			                   	    <%= image_tag 'cigarette.jpg', size:'30x30', class: "icon_tag" %>
			                   	    <%= @diary.cigarette %>本
			                   </span>
			                   <span class="show_icon">
			                   	    <%= image_tag 'drinking.png', size:'30x30', class: "icon_tag" %>
			                   	    <%= @diary.drinking %>缶
			                   </span>
			            </div>
            </p>
            <p class="sentiment-score">
              <% if @diary.score == nil %>
                この日記にはスコアがありません
              <% else %>
                日記の感情分析スコア<%= @diary.score %>点
              <% end %>
            </p>
      		</div>
      	</div>
      </div>
  </div>
  <div class="row">
      <div class="col-md-7 col-sm-7 col-xs-12">
      		  <h2>コメント一覧</h2>
          		<% if @diary.comments.count == 0 %>
          		   <p>この記事にはまだコメントはありません。コメントしてみましょう！</p>
          		<% end %>
      		<div class="box2">
              <%= render 'diaries/comment-area', comments: @diary.comments %>
          </div>

    	    <%= form_for [@diary, @comment] do |f| %>
    	      <%= f.text_area :comment, size: "90x5", class: 'form-control diary-body' %>
    	      <%= f.submit '送信', class: "btn btn-info form-control" %>
    	    <% end %>
      </div>
  </div>
</div>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>