config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :diaries do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :notifications, only: :index
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :index, :show]
  resources :events

  delete '/notifications/destroy_all' => 'notifications#destroy_all'
  get 'users/:id/favorites' => 'users#favorites', as: 'user_favorites'
  get 'users/:id/graphs' => 'users#graphs', as: 'user_graphs'
  get 'search' => 'search#search'
  get 'my_calendar', to: 'events#my_calendar'
  root 'homes#top'
  get 'home/about' => 'homes#about'
end

app/views/layouts/_member-head.html.erb
<li style="margin-top: 10px;">
	<%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'search[content]' %>
        <%= select_tag 'search[model]', options_for_select({ "ユーザー" => "user", "投稿一覧" => "diary"}) %>
        <%= submit_tag '検索' %>
    <% end %>
</li>
 <% if unchecked_notifications.any? %>
    <i class="fa fa-circle" style="color: gold;"></i>
<% end %>
<li><a href="#"><%= link_to "通知", notifications_path, class: "glyphicon glyphicon-bell" %></a></li>
<li><a href="#"><%= link_to 'マイページ', user_path(current_user), class: 'glyphicon glyphicon-home home', id: 'introjs-step9' %></a></li>
<li><a href="#"><%= link_to '新規投稿', new_diary_path, class: 'glyphicon glyphicon-plus', data: {"turbolinks" => false} %></a></li>
<li><a href="#"><%= link_to '投稿一覧', diaries_path, class: 'glyphicon glyphicon-book books' %></a></li>
<li><a href="#"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QOH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => "reload" %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <script src="https://kit.fontawesome.com/d23a94ca31.js" crossorigin="anonymous"></script>
  </head>

  <body class="background">
   <div id="wrapper">
    <header class="navbar navbar-fixed-top navbar-inverse" style="background-color: #90EE90;">
      <div>
        <%= link_to home_about_path do %>
        <nav class="nav navbar-nav navbar-left">
          <span class="site_name">QOH<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></span><span class="site_name_min">  quality~of~health</span>
        </nav>
        <% end %>
        <nav>
          <div id="sp-menu">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                  <%= render 'layouts/member-head' %>
              <% else %>
                  <%= render 'layouts/guest-head' %>
              <% end %>
            </ul>
          </div>
        </nav>

        <div id="hm-icon">
             <a class="menu-trigger" href="#">
                <span></span>
                <span></span>
                <span></span>
             </a>
        </div>

      </div>
    </header>
    <%= yield %>
    <footer>
      <p class="footer_text">©︎All rights reserved by QOH.</p>
    </footer>
   </div>
  </body>
</html>